site_name: Niv Edition

theme: 
  name: dracula
    
  font:
    text: Signika
    code: Roboto Mono
    
  # Enhance the navigation layout
  features:
    - navigation.tabs         # Creates top-level navigation tabs
    - navigation.sections     # Groups sidebar items into neat sections
    - navigation.top          # Adds a "Back to Top" button when scrolling
    - search.suggest          # Auto-suggests search terms
    - toc.integrate           # MERGES the Table of Contents into the left sidebar

  extra_css:
    - stylesheets/custom.css