site_name: Niv Edition
site_url: https://Novalmauge.github.io/Niv_Edition/

theme: 
  name: dracula
  favicon: assets/favicon.ico
  custom_dir: overrides
nav:
  - Home: index.md
  - About the DM: about.md
  - Variant Rules: 
    - Character Creation: variant-rules/character.md
    - Combat:  variant-rules/combat.md
    - Inventory: variant-rules/inventory.md
    - Attunement Slots: variant-rules/attunement.md
  - Classes: 
    - Classes: classes/classes.md
    - Sidekick Classes: classes/sidekick_class.md
    - Prestige Classes: classes/prestige_class.md
  - Feats: 
    - General Feats: feats/general_feats.md
    - Racial Feats: feats/racial_feats.md
    - Origin Feats: feats/origin_feats.md
    - Boons: feats/boon_feats.md
  - Spells: 
    - Spell Changes: spells/spell_changes.md
    - Spell Lists: spells/spelllist.md
    - Abjuration: spells/abjuration.md
    - Conjuration: spells/conjuration.md
    - Divination: spells/divination.md
    - Enchantment: spells/enchantment.md
    - Evocation: spells/evocation.md
    - Illusion: spells/illusion.md
    - Necromancy: spells/necromancy.md
    - Transmutation: spells/transmutation.md
  - Equipment & Items: 
    - Bastions: equipment/bastions.md
  - Playable Species: species.md
  - Campaign Info:
    - Overview: campaign/overview.md
    - The World of Halione: campaign/halione/halione.md
    - Numana: campaign/numana/numana.md
    - The World Dungeon: 
      - Overview: campaign/world_dungeon/world_dungeon.md
    - Beastlands: 
      - Overview: campaign/beastlands/beastlands.md
    - New Wightlaw: 
      - Overview: campaign/new_wightlaw/new_wightlaw.md

extra_css:
 - stylesheets/custom.css